//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Proj.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUTNI_NALOZI
    {
        public int IDNalog { get; set; }
        public Nullable<System.DateTime> Otvaranje { get; set; }
        public Nullable<System.DateTime> Zatvaranje { get; set; }
        public Nullable<int> VozacID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public Nullable<int> MjestoStartID { get; set; }
        public Nullable<int> MjestoCiljID { get; set; }
        public Nullable<int> StatusNaloga { get; set; }
    
        public virtual GRADOVI GRADOVI { get; set; }
        public virtual GRADOVI GRADOVI1 { get; set; }
        public virtual VOZACI VOZACI { get; set; }
        public virtual VOZILA VOZILA { get; set; }
    }
}
