//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Proj.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVISNA_KNJIGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVISNA_KNJIGA()
        {
            this.SERVISI = new HashSet<SERVISI>();
        }
    
        public int IDServis { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public System.DateTime Datum { get; set; }
        public decimal Trosak { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVISI> SERVISI { get; set; }
        public virtual VOZILA VOZILA { get; set; }
        public override string ToString() => $"{Datum.ToString("dd/MM/yyyy")}";
    }
}
