//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Proj.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVIS_STAVKE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVIS_STAVKE()
        {
            this.SERVISI = new HashSet<SERVISI>();
        }
    
        public int IDStavka { get; set; }
        public string Naziv { get; set; }
        public decimal Cijena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVISI> SERVISI { get; set; }

        public override string ToString() => $"{Naziv}: {Cijena} kn";
    }
}
