//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_Proj.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOZILA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOZILA()
        {
            this.PUTNI_NALOZI = new HashSet<PUTNI_NALOZI>();
            this.SERVISNA_KNJIGA = new HashSet<SERVISNA_KNJIGA>();
        }
    
        public int IDVozilo { get; set; }
        public string Marka { get; set; }
        public string Tip { get; set; }
        public System.DateTime GodinaProizvodnje { get; set; }
        public System.DateTime GodinaUnosa { get; set; }
        public int InicijalniKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUTNI_NALOZI> PUTNI_NALOZI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVISNA_KNJIGA> SERVISNA_KNJIGA { get; set; }
        public override string ToString() => $"{Marka} {Tip}";
    }
}
